#pragma once

#include <cstdint>
#include <vector>

#include <glm/vec2.hpp>

namespace civitasx
{

    namespace graphics
    {

        // Classic Bresenham line algorithm.
        // Returns integer pixel coordinates from (x0, y0) to (x1, y1).
        std::vector<glm::ivec2> buildLinePointsBresenham(int x0, int y0, int x1, int y1);

        // Rectangle fill using scanlines generated by Bresenham lines.
        // Each row is drawn as a horizontal line, so the final tile is fully filled by algorithm output.
        std::vector<glm::ivec2> buildFilledRectPoints(int x, int y, std::int32_t width, std::int32_t height);

        // Builds a triangle-fan friendly vertex list for a filled circle.
        // Boundary points are produced via the Midpoint Circle algorithm.
        std::vector<glm::vec2> buildCircleFanVertices(const glm::vec2 &center, float radius, int segments);

    } // namespace graphics

} // namespace civitasx
